name: yolov4-gpu

dependencies:
  - python==3.7.2
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu==2.2
    - opencv-python==4.1.1.26
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - pafy==0.5.5
    - youtube-dl==2021.6.6
