# Generated by Django 3.2.18 on 2023-09-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('total_count', models.PositiveIntegerField(null=True)),
                ('up_count', models.PositiveIntegerField(null=True)),
                ('down_count', models.PositiveIntegerField(null=True)),
                ('class_counts', models.JSONField(default=dict)),
                ('class_counter', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255, null=True)),
                ('total_count', models.PositiveIntegerField(null=True)),
                ('up_count', models.PositiveIntegerField(null=True)),
                ('down_count', models.PositiveIntegerField(null=True)),
                ('class_counts', models.JSONField(default=dict)),
                ('class_counter', models.JSONField(default=dict)),
            ],
        ),
    ]
